# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Livvi Karelian spellchecker"
olo = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Livvi Karelian, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
olo = "TRANSLATE: A spellchecker for Livvi Karelian, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.olo"

[windows]
system_product_code = "{BCB6B629-E478-4945-A694-76A975840B3D}_is1"
legacy_product_codes = [
    { value = "4B4C328A-1C7F-40A0-8854-C17EB64DC8BD", kind = "nsis" },
    { value = "6A340BF1-4D72-4D9B-9154-4209918910D5", kind = "nsis" }
]

[package.speller]
name = "Livvi Karelian"
version = "0.1.2"

[package.grammar]
name = "Livvi Karelian"
version = "0.1.0"

[package.tts-textproc]
name = "Livvi Karelian"
version = "0.1.0"

[package.hyphenator]
name = "Livvi Karelian"
version = "0.1.0"
