template = "https://github.com/giellalt/template-lang-und"
rev_id = 254
template_sha = "9eb2a95995f59cb63a159a5cc7bcce8f049babe4"

[replacements]
__GLOTTOLOG_ID__ = "livv1243"
__REPO__ = "lang-olo"
__UND2C__ = "olo"
__UNDEFINED__ = "Livvi Karelian"
__UND__ = "olo"
