template = "https://github.com/giellalt/template-lang-und"
rev_id = 252
template_sha = "00bea80a90b92870230cbd76cf7ed0fece87f2c0"

[replacements]
__GLOTTOLOG_ID__ = "livv1243"
__REPO__ = "lang-olo"
__UND2C__ = "olo"
__UNDEFINED__ = "Livvi Karelian"
__UND__ = "olo"
