template = "https://github.com/giellalt/template-lang-und"
rev_id = 280
template_sha = "6beee360d8349c39749ac477719ead241493924c"

[replacements]
__GLOTTOLOG_ID__ = "livv1243"
__REPO__ = "lang-olo"
__UND2C__ = "olo"
__UNDEFINED__ = "Livvi Karelian"
__UND__ = "olo"
